### ISSUE TITLE
bug in 'homolog.lib'

### ISSUE THREAD

**Issue by jakobkroeker** [jakobkroeker/test_singular#140]
Singular/LIB/homolog.lib:536:      if (size(M)==0) { attrib(M,"isSB")=1; }

should it be 

`if (size(M)==0) { attrib(M,"isSB", 1 ); }`

or even 

`if (size(M)==0) { M = std(0); }`

since M could be = [0,0,0]; or similar?

**Comment by fruhbis-kruger-anne** [comment]
just the attrib , which you suggested, should do the job -- zero does not provide any leading monomial no matter in what embedding.

**Comment by jakobkroeker** [comment]
fixed by Hans with 
https://github.com/Singular/Sources/commit/97a7da2750245efc953ff12aad2e56a4bff4374e
