### ISSUE TITLE
incorrect test, or not reduced tail

### ISSUE THREAD

**Issue by jakobkroeker** [jakobkroeker/test_singular#153]
result is the same for spielwiese and for recent SignaturesB

```
LIB "primdec.lib";
LIB "wrappers.lib";
ring rng = (integer),(x,y,z),(dp(3),C);
intvec op = 100663424,16787537;
option(set, op) ;
option() ;
system("random", 1250511850);
ideal I = y^2+y*z+4,-3*y-8*z;
ideal gI =  std(I);
 gI;
ASSUME(0, idealRepresentationReducedTail(gI ) );
```

output (look at yz):

```
gI[1]=3y+8z
gI[2]=40z2+36
gI[3]=yz+16z2+12
gI[4]=y2+yz+4
```

**Comment by fruhbis-kruger-anne** [comment]
no TailReduction! 
Tail Reduction (largely) disabled over the integers, because this is a massive source of coefficient swell.

**Comment by jakobkroeker** [comment]
> Tail Reduction (largely) disabled over the integers

Good to know; 
I'm fine in case it is disabled by default (and would support that)

However, in case  that  tail reduction it is explicitly set, it should behave as requested (?)

**Comment by jakobkroeker** [comment]
invalid report, see
http://www.singular.uni-kl.de:8002/trac/ticket/702
